### ISSUE TITLE
RecommendationArchiveModel::findBySyncWithGoogle() is not implemented

### ISSUE THREAD

**Issue by danielkochc** [oveleon/contao-google-recommendation-bundle#1]
The static RecommendationArchiveModel method findBySyncWithGoogle() called in vendor\oveleon\contao-google-recommendation-bundle\src\Resources\contao\classes\GooglePlacesApi.php::22 has no implementation, so the api can never run successfully.

**Comment by eki89** [comment]
Hello danielkockc,
you are right. The called method can't exist in the actual model. I'll fix the problem in the coming days.

**Comment by eki89** [comment]
I've fixed the problem in release 1.1

In addition i've added a new field to select the language for synced recommendations. The default value is en,  so you need to change it to de manually.
