### ISSUE TITLE
Add the possibility to import reviews without text

### ISSUE THREAD

**Issue by cliffparnitzky** [oveleon/contao-google-recommendation-bundle#11]
The extension currently only allows the import of reviews with an entered text. If there is no text vavailable, the importer will skip the review.

It would be great to have the possibility to configure this.

**Comment by cliffparnitzky** [comment]
Maybe the simplest way ist to set `[nbsp]` ... this prevents any changes in the backend or templates.

**Comment by zoglo** [comment]
Would you be able to test this feature @cliffparnitzky?

```    
"require": {
    "oveleon/contao-recommendation-bundle": "dev-main as 1.5",
    "oveleon/contao-google-recommendation-bundle": "dev-main"
    ...
}
 ```
or
```    
"require": {
    "oveleon/contao-recommendation-bundle": "dev-develop as 1.5",
    "oveleon/contao-google-recommendation-bundle": "dev-develop"
    ...
}
 ```
 
 See:
 - https://github.com/oveleon/contao-google-recommendation-bundle/commit/8f30f53808ca2b74e1b7d88f5f1f82c2a692a369
 - https://github.com/oveleon/contao-recommendation-bundle/commit/ac0a076d3da6f07e037da345e1e4c2b42222adf2
 
 This release will also require version 1.5 of the recommendation-bundle -> See: https://github.com/oveleon/contao-recommendation-bundle/milestone/1

**Comment by cliffparnitzky** [comment]
Works well. Thanks.

**Comment by zoglo** [comment]
Added in 8f30f53808ca2b74e1b7d88f5f1f82c2a692a369
