### ISSUE TITLE
for Schleife für Sterne recommendation_full.html5

### ISSUE THREAD

**Issue by codesache** [oveleon/contao-google-recommendation-bundle#13]
### Prerequisites

- [X] I [checked](https://github.com/oveleon/contao-google-recommendation-bundle/issues?q=is%3Aissue) for duplicate issues (open and closed)
- [X] I am using the latest stable [version/release](https://packagist.org/packages/oveleon/contao-recommendation-bundle) of the Contao Recommendation Bundle
- [X] I am using the latest stable [version/release](https://packagist.org/packages/oveleon/contao-google-recommendation-bundle) of the Contao Google Recommendation Bundle
- [X] I have read the [contributing guidelines](https://github.com/oveleon/contao-recommendation-bundle#bugs-and-feature-requests)

### Please select the topic(s) that most closely match your concern

Template (HTML/Twig)

### Description

Könnt ihr euch in dem Template recommendation_full.html5 bei der for Schleife ansehen. Hier steht ein fester Wert 5 was dann in der Liste immer 5 Sterne ausgeben wird. 

Ich habe die Schleife mit $i<= $this->rating geändert, dann wird die richte Anzahl der Sterne gelistet.

### Relevant log output

```shell
<?php if ($this->rating): ?>
   <div class="ratingsterne">
    <span class="rating rating_<?= $this->rating ?>">
    <?php for ($i=1;$i<= $this->rating;$i++): ?>
     <span class="star<?= ($i<=$this->rating) ? ' active' : '' ?>"<?= ($i<=$this->rating && $this->styles) ? $this->styles  : '' ?>>&#9733;</span>
    <?php endfor; ?>
    </span>
   </div>
<?php endif; ?>
```

**Comment by zoglo** [comment]
@codesache
This is intended and isn't a bug in this bundle but a feature in https://github.com/oveleon/contao-recommendation-bundle/

See [Setting up colors for your recommendation rating](https://github.com/oveleon/contao-recommendation-bundle/?tab=readme-ov-file#initial-setup:~:text=Setting%20up%20colors%20for%20your%20recommendation%20rating)
![image](https://github.com/oveleon/contao-google-recommendation-bundle/assets/55794780/1df6c00c-8a65-4c1c-8d14-bf7b9aead739)


The amount of rating adds the class **active** and a color if it has been set up.
