### ISSUE TITLE
FR: Widget for total values

### ISSUE THREAD

**Issue by neckarpixel** [oveleon/contao-google-recommendation-bundle#4]
Thanks for that extension. Works fine!

One feature request: a widget with a summary of all entries (e.g. 4,5 stars in total of XXX entries).
Atm I use an adjusted mod_recommendationlist template.

**Comment by zoglo** [comment]
Hello @neckarpixel ,

are you referring to getting the actual average rating from google maps (with rating count) or do you mean the average ratings of an archive out of the base bundle: https://github.com/oveleon/contao-recommendation-bundle?

**Comment by neckarpixel** [comment]
> are you referring to getting the actual average rating from google maps (with rating count) or do you mean the average ratings of an archive out of the base bundle: https://github.com/oveleon/contao-recommendation-bundle?

To be honest, firstly I only thought about the Google Ratings but when you think about it, in both cases it can be really useful to have a summary.

**Comment by zoglo** [comment]
Importing *user_ratings_total* and the *rating* itself is possible via the maps API. However, as we only import the last 5 ratings, you won't be able to get older ratings anymore. IMHO, the total rating (from google) should only be visible in google maps.

I'd rather suggest to have something that will get the total of published ratings out of a recommendation archive to have more control over it. Could also be included into the Recommendation-List module.
WDYT?

**Comment by neckarpixel** [comment]
As I read in the docs, that only Google Business Account can receive all comments.

But I really love the idea to have a total count of alle ratings. 

Thanks!
